<a href="https://colab.research.google.com/github/katusabevictoria/katusabevictoria/blob/main/Pandas_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loops Exercise -  Core


# Task 1: Loop through a list

A company sells the following items at the given prices:

Shirts 10.00

Hats 15.00

Buttons 4.00

Stickers 1.00

TO DO:

A: Run the pre-coded cell to create a list of the products.

B: Write a for-loop and use an f-string to print "We sell PRODUCT here!" for each product in the list.




In [1]:
# Create a list of products
products = ['Shirts', 'Hats', 'Buttons', 'Stickers']

In [2]:
# Create a list of products
products = ['Shirts', 'Hats', 'Buttons', 'Stickers']

In [6]:
products = ['Shirts', 'Hats', 'Buttons', 'Stickers']
print (products)

['Shirts', 'Hats', 'Buttons', 'Stickers']


In [ ]:
# Write a for-loop to repeat the print statement for each product in the list.


In [4]:
products = ['Shirts', 'Hats', 'Buttons', 'Stickers']
for item  in  products:
  item  = products
  print(item)

['Shirts', 'Hats', 'Buttons', 'Stickers']
['Shirts', 'Hats', 'Buttons', 'Stickers']
['Shirts', 'Hats', 'Buttons', 'Stickers']
['Shirts', 'Hats', 'Buttons', 'Stickers']


#Task 2: Use a loop to append values to a new list

The products are going on a 20% off sale!  


TO DO:

A: Run the precoded cell to create the list of original
B: Define an empty list called sale_prices

C: Write a for-loop to append values to the sales_prices list that reflect the sale price (original price * 0.8)

D: Print the new list of sales_prices

In [ ]:
# Create a list of the prices.
original_prices = [10, 15, 4, 1]

In [ ]:
# Create an empty list called sale_prices


In [2]:
# Use a loop to append the sale_prices list with the sale price (a 20% discount means the original price is multiplied by .8)
names_list = ['brownie','cookie','cake', 'cupcake']
names_list

['brownie', 'cookie', 'cake', 'cupcake']

In [3]:
# Print the list of sale_prices
prices_list = [2.25,1.25,9.5, 3.5]
prices_list

[2.25, 1.25, 9.5, 3.5]

In [4]:
quantities_sold_list = [17, 40, 1, 10]
print(quantities_sold_list)

[17, 40, 1, 10]


In [6]:
# import numpy
import numpy as np
# make a numpy array from the prices list
prices_array = np.array(prices_list)
prices_array

array([2.25, 1.25, 9.5 , 3.5 ])

In [7]:
quantities_sold_array = np.array(quantities_sold_list)
quantities_sold_array

array([17, 40,  1, 10])

In [8]:
prices_array * quantities_sold_array

array([38.25, 50.  ,  9.5 , 35.  ])

#Task 3: Loop through a dictionary

TO DO:

A: Run the pre-coded cell to create the prices_dict.

B: Loop through the prices_dict and use an f-sting to print the statement: "We sell PRODUCT!"

C: Loop through the prices_dict using prices_dict.items() to print the statement "PRODUCT costs $PRICE each." for each product in the dictionary.

In [ ]:
# Run this cell to create a dictionary with product and price
prices_dict = {'Shirts': 10,
              'Hats': 15,
              'Buttons' : 4,
              'Stickers' : 1}

prices_dict

In [ ]:
# Loop through the dictionary to print: "We sell __!"


In [ ]:
# Loop through the dictionary to print: "__ cost $__ each".


#Task 4: Create a new dictionary by updating values using a for-loop

We want to create a new dictionary that contains the product and the sale price called sale_dict.

To create the prices_dict in the above task, we just provided the code cell with the necessary information. Rather than typing all of the info to make the sale dictionary, we will use a for-loop to calculate the sale price based on the original price.

TO DO:

A: Create an empty dictionary called sales_dict.

B: Use a for-loop and prices_dict.items() to fill in the sales_dict.

* Calculate the sale price (original price * 0.8).

* Save the sale price in the sales_dict using the product name as the key.

C: Print the sales_dict

D: Loop through the sales_dict.items() to print "PRODUCT are on sale for only SALE PRICE!'




In [ ]:
# Use a loop to create a new dictionary with product and sales prices


In [ ]:
# Print the sales_dict


In [ ]:
# Loop throuh the sale_dict to print "PRODUCT are on sale for only SALE PRICE!" for each item.


In [9]:
import pandas as pd

In [12]:
df = pd.DataFrame({'Name':names_list,
                   'Price':prices_list,
                   "Quantity Sold": quantities_sold_list})
df

Name  Price  Quantity Sold
0  brownie   2.25             17
1   cookie   1.25             40
2     cake   9.50              1
3  cupcake   3.50             10

In [15]:
df.columns

Index(['Name', 'Price', 'Quantity Sold'], dtype='object')

In [16]:
df.values

array([['brownie', 2.25, 17],
       ['cookie', 1.25, 40],
       ['cake', 9.5, 1],
       ['cupcake', 3.5, 10]], dtype=object)

In [17]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [39]:
df.set_index("Price")


Name  Quantity Sold
Price                        
2.25   brownie             17
1.25    cookie             40
9.50      cake              1
3.50   cupcake             10

In [40]:
df

Name  Price  Quantity Sold
0  brownie   2.25             17
1   cookie   1.25             40
2     cake   9.50              1
3  cupcake   3.50             10

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [46]:
fname ="/content/sample_data/california_housing_test.csv"
df = pd.read_csv(fname)

In [49]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [50]:
df.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0

In [55]:
names_list = ['1','2','3', '4']
names_list

['1', '2', '3', '4']

In [52]:
prices_list = [2.25,1.25,9.5, 3.5]
prices_list

[2.25, 1.25, 9.5, 3.5]

In [53]:
quantities_sold_list = [17, 40, 1, 10]
print(quantities_sold_list)

[17, 40, 1, 10]


In [56]:
prices_list * quantities_sold_list

TypeError: can't multiply sequence by non-int of type 'list'

In [57]:
import numpy as np

In [62]:
prices_array = np.array(prices_list)
prices_list

[2.25, 1.25, 9.5, 3.5]

In [63]:
quantities_sold_array = np.array(quantities_sold_list)
quantities_sold_list

[17, 40, 1, 10]

In [61]:
prices_array * quantities_sold_array

array([38.25, 50.  ,  9.5 , 35.  ])